on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
          submodules: true
      - name: Test
        run: |
          sh ./test.sh
